sudo: required
services:
    - docker
script:
    - do/all
deploy:
    skip_cleanup: true
    api_key:
        secure: fXQqOZTT0MxROBeNcCqnk1XVJ8v82LS3c+cKj+IaDyNepwuTdPDNOSt6DvhkPy8wRqsxbaVTO2r305Fgdvj+EIC77NlCUaL3IVhOKiP6d+JOf4ZNLvaqq3esv/33CVETfJCs7+vtnqykPwrkZ6v1fIdjhhT3YcMPV4hieB0dpjIRcSuk+nnelPc0I6ClxXG8pGKRmrj4qFWGTGaTgbbqasb5rrDCgy48bZ8m0CBoPbhdaCLzBOA51onYVs/RyqNi91NnlLDZxFE0J361V5eVQmdWCGsL5AzcE0wpuhwZY6wnQwmld+SDYSueGaEcyhTYMbXkAfqYe4OONyDYEVUthSLKZtio4qDVhYkqiVcPjgg6QcBJGHy4pYqLXp9xg9Epi7R74cBPh2zFEwudoCf6bmcNBH96/j+ASoW8MIVAzFuHCQ8NYIfwYVgaD9H/o9LEYVtaeI58zkzknydXA6sefpQryEqQEkOnVKEgs1Z1KsAhtQn8/EyQhG1fNSru4hFd1gpd+hYqd8lch5pN2QJPk9X1pp4VGr4ui0MnWFW4TuAd3xhyyO3iCHV1RsHl6IAELEkX5s7GZYydDt/7AgZgerVmyBfYMtyMDXUGwRayhxic8rSBo0EpwfukRay/v+2xlYTYuuYJObAJBJDlBb1dDHoDULeczT4CA+mfhl26hG8=
    provider: releases
    file: build/resu
    on:
        tags: true
