#!/bin/bash -eu
set -o pipefail

do_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
. "$do_dir/mkdo.sh"

source_dir="$(dirname -- "$do_dir")"
output_dir="${source_dir}/acceptance-test"

run_in_docker --with-docker-in-docker \
    --volume="$source_dir:$source_dir:ro" \
    --volume="$output_dir:$output_dir:rw" \
    --workdir="$output_dir" \
    resu/acceptance-test

if [[ -t 1 ]]; then
    if behave ../features; then
        echo -e "\e[92;1m   A_A
 =(o.o)=    ,
 (  _  )--'
  !! !!      SUCCESS!\e[0m"
    else
        echo -e "\e[91;1m   A_A
 =(x.x)=    ,
 (  _  )--'
  !! !!      FAIL.\e[0m"
        exit 1
    fi
else
    behave ../features
fi
