#!/bin/bash -eu
set -o pipefail

do_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
. "$do_dir/mkdo.sh"

source_dir="$(dirname -- "$do_dir")"
output_dir="$source_dir/build"

if [ ! -d "$output_dir" ]; then
    mkdir -p "$output_dir"
fi

run_in_docker \
    --volume="$source_dir:$source_dir:ro" \
    --volume="$output_dir:$output_dir:rw" \
    --workdir="$output_dir" \
    resu/build

cmake ..
make
