#!/bin/bash -eu
set -o pipefail

do_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
. "$do_dir/mkdo.sh"

source_dir="$(dirname -- "$do_dir")"
output_dir="$source_dir/build-alpine"

run_in_docker \
    --volume="$source_dir:$source_dir:ro" \
    --volume="$output_dir:$output_dir:rw" \
    --workdir="$output_dir" \
    resu/build-alpine

cmake -DRESU_EXECUTABLE:STRING=resu-alpine ..
make
