#!/bin/bash -eu
set -o pipefail

do_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

user="$(id -nu)"
group="$(id -ng)"
uid=$(id -u)
gid=$(id -g)

upsert_group()
{
    local gid="$1"
    local group="$2"
    echo "getent group $gid && groupmod --new-name $group \$(getent group $gid | cut -f 1 -d :) || groupadd --gid $gid $group"
}

root_docker="$1"
user_docker="$1-user"

user_docker_dir="$do_dir/.mkdo-$(echo "$user_docker" | sed -e 's,/,-,g')"
if [[ -e "$user_docker_dir" ]]; then
    rm -rf "$user_docker_dir"
fi
mkdir "$user_docker_dir"

if [[ ${2-} = --with-docker ]]; then
    docker_in_docker="
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        docker.io
"
    if [[ $(uname -s) = Linux ]]; then
        outer_docker_gid=$(getent group docker | cut -f 3 -d :)
        docker_in_docker="$docker_in_docker
RUN $(upsert_group $outer_docker_gid docker_in_docker)
RUN usermod -aG docker_in_docker $user"
    else
        # FIXME: No docs behind this magical group -- may change with Docker for Mac beta...
        docker_in_docker="$docker_in_docker
RUN groupadd --gid 50 docker_in_docker
RUN usermod -aG docker_in_docker $user"
    fi
fi

cat > "$user_docker_dir/Dockerfile" <<EOF
FROM $root_docker

RUN getent group $group && groupdel $group || true
RUN $(upsert_group $gid $group)
RUN useradd $user --uid $uid --gid $gid --create-home

${docker_in_docker-}

USER $user
EOF

echo -n "User Docker: "
docker build ${DOCKER_QUIET-} \
       --force-rm --rm=true \
       -t "$user_docker" \
       "$user_docker_dir"
