#!/bin/bash -eu
set -o pipefail

do_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

user="$(id -nu)"
group="$(id -ng)"
uid=$(id -u)
gid=$(id -g)

upsert_group()
{
    local gid="$1"
    local group="$2"
    echo "getent group $gid && groupmod --new-name $group \$(getent group $gid | cut -f 1 -d :) || groupadd --gid $gid $group"
}

if [[ $(uname -s) = Linux ]]; then
    outer_docker_gid=$(getent group docker | cut -f 3 -d :)
    docker_in_docker="
RUN $(upsert_group $outer_docker_gid docker_in_docker)
RUN usermod -aG docker_in_docker $user"
else
    # FIXME: No docs behind this magical group -- may change with Docker for Mac beta...
    docker_in_docker="
RUN groupadd --gid 50 docker_in_docker
RUN usermod -aG docker_in_docker $user"
fi

root_docker="$1"
user_docker="$1-user"

user_docker_dir="$do_dir/.mkdo-$user_docker"
if [[ -e "$user_docker_dir" ]]; then
    rm -rf "$user_docker_dir"
fi
mkdir "$user_docker_dir"

cat > "$user_docker_dir/Dockerfile" <<EOF
FROM $root_docker

RUN getent group $group && groupdel $group || true
RUN $(upsert_group $gid $group)
RUN useradd $user --uid $uid --gid $gid

$docker_in_docker

USER $user
EOF

echo -n "User Docker: "
docker build \
       --force-rm --rm=true \
       -t "$user_docker" \
       "$user_docker_dir"
